site_name: http://kevellpht.readthedocs.org
include_search: true
theme_dir: ./theme/mkdocs/
theme_center_lead: false
pages:
- [index.md, Home]
- [about.md, About]
- [Introduction.md, Introduction]
- [Installation.md, Installation]
- [Cleopatra/Cleopatra.md, Cleopatra]
- [Phlagrant/Phlagrant.md, Phlagrant]
- ["Getting Started.md", "Getting Started"]
theme:  ghostwriter
