site_name: http://kevellpht.readthedocs.org
pages:
- [index.md, Home]
- [about.md, About]
- [Introduction.md, Introduction]
- [Installation.md, Installation]
- [Cleopatra/Cleopatra.md, Cleopatra.md]
- [Phlagrant/Phlagrant.md, Phlagrant.md]
- ["Getting Started.md", "Getting Started"]
theme: readthedocs
